export const GETUSER_REQ = "GETUSER_REQ";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAILURE = "GETUSER_FAILURE";

export const GETCART_REQ = "GETCART_REQ";
export const GETCART_SUCCESS = "GETCART_SUCCESS";
export const GETCART_FAILURE = "GETCART_FAILURE";

export const GETWISHLIST_REQ = "GETWISHLIST_REQ";
export const GETWISHLIST_SUCCESS = "GETWISHLIST_SUCCESS";
export const GETWISHLIST_FAILURE = "GETWISHLIST_FAILURE";